branches:
  only:
    - develop

language: node_js

sudo: false

node_js: lts/*

cache:
  directories:
    - node_modules

# https://github.com/juliangruber/electron-stream#travis
addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install

before_script:
  - git config --global user.name "viko16"
  - git config --global user.email "16viko@gmail.com"
  - git clone --branch gh-pages https://${GH_REF} dist

script:
  - npm test

after_success:
  - npm run build
  - cd dist
  - echo "ukn.me" > CNAME
  - cp index.html 404.html
  - git add --all .
  - git commit --message "Automatically update from travis-ci"
  - git push --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages

# Note: you should set Environment Variables here or 'Settings' on travis-ci.org
env:
  global:
    - GH_REF: github.com/viko16/vue-ghpages-blog.git
    # - GH_TOKEN: 'Your GitHub Personal access tokens, via https://github.com/settings/tokens'
